### ISSUE TITLE
tomcat 6 commit log message always writes "commited key:null"

### ISSUE THREAD

**Issue by jethroindc** [hazelcast/hazelcast-tomcat-sessionmanager#27]
When saving the session back to the sessionMap in the tomcat6 flavor of com.hazelcast.session.HazelcastSessionManager, the log message writes the value of  hazelcastSession.getAttribute("key") which looks to be a relic from testing.  The other implementations for Tomcat7, Tomcat8 and Tomcat85 all log the expected value of the session id.  Will create a pull request and submit shortly.

**Comment by emre-aydin** [comment]
Hi @jethroindc 

The reason we have fixed this for other versions but not Tomcat 6 is that we will drop support for Tomcat 6 in the near future (because Tomcat 6 itself has reached EOL). Are you using Tomcat 6 and the plugin together? If so, what's the reason holding you back from upgrading to newer Tomcat versions? It's important for us to know.

Thanks.

**Comment by jethroindc** [comment]
We are using Tomcat6 and the plugin.  We're working on getting to a more
modern version of Tomcat but will  probably be another 6 months before we
can move.  We're currently running our website using OpenText portal and
WEM and it's a big lift to get from one version to the next, hence our
outdated Tomcat.
