### ISSUE TITLE
Why session manager doesn't use replicated map?

### ISSUE THREAD

**Issue by nikoncode** [hazelcast/hazelcast-tomcat-sessionmanager#35]
In my project we use embedded instances of hazelcast, as I understand from codebase session manager uses regular distributed map for session replication, but what if I execute rolling restart of my application (with embedded hazelcast)?

I expect session pick up on any available instance, but session manager uses distributed map. It leads to session data lost.

**Comment by mesutcelik** [comment]
Hi @nikoncode 
`ReplicatedMap` is completely different data structure than Hazelcast Distributed Map, named `IMap`.  

Distributed Map is partitioned data structure whereas ReplicatedMap does replicate all data to other members. Therefore, we have preferred to use Distributed Map because of the Memory consumption. 

If you want to rolling restart without losing data, we suggest to restart nodes one by one and wait until migrations are completed before taking down the subsequent node.

please check following links for healthy rolling restarts.
http://docs.hazelcast.org/docs/latest/manual/html-single/#rolling-upgrade-procedure
http://docs.hazelcast.org/docs/latest/manual/html-single/#safety-checking-cluster-members

please check below when you consider using Replicated Map
http://docs.hazelcast.org/docs/latest/manual/html-single/index.html#considerations-for-replicated-map

We have no plans for Replicated Map usage as Session Store so I am closing this issue now. 
I also suggest you to use [Google Group](https://groups.google.com/forum/#!forum/hazelcast) for any Hazelcast related questions.
